### ISSUE TITLE
Beluga naming conventions

### ISSUE THREAD

**Issue by fferreira** [Beluga-lang/Meta#2]
In STYLE.md I filled a proposed naming convention for Beluga code. Closely following the TAPL conventions does not work in Beluga because they use case distinctions for different categories (e.g: t for terms / T for types) and that clashes with Beluga's requirements for variable naming. In this situation, I propose to use "our conventional" names, that relate to Twelf and also to the examples that Beluga is distributed with. After all, the purpose of the book is to introduce readers to mechanizing their problems with Beluga, it is natural that we introduce the usual Beluga naming conventions. 

Having said this, probably there are issues with my proposal. Please check it out and fix/change my suggested names to better fit the book.

I filed this issue as a question, I will close it after the STYLE.md seems to have converged (If there is no feedback I'll assume it converged already).

Cheers,
Francisco

**Comment by Niols** [comment]
Two little things to note:
1. We also have to work with numeric values. Do we only consider them as values, or do we use a special naming convention for them?
2. In TAPL, you often find terms `t_1, t_2, …`. Even when it's not necessary (`iszero t1 → iszero t1'`). What is the Beluga equivalent? `M1`? `M_1`? …

Maybe more feedbacks soon

**Comment by fferreira** [comment]
For number 1, you can add more entries if needed. However, we should not make unncessary distinctions, if V and W suffice for numerical values don't add anything. If you think that a new category is necessary then add it.

Wether to use primes or 1,2 for names is discussed in section 3 of STYLE.md Beluga code should follow the same pattern. However, for numbers we should avoid the underscore. We want M1 not M_1

**Comment by fferreira** [comment]
I updated the STYLE.md with some suggestions by Brigitte and Nicolas. I am now closing this issue and consider STYLE.md as a baseline for choosing your names of things
